In [1]:
import os

# Need to set at Project home
os.chdir("/Users/yoonseojin/Statistics_sj")
from File_Package.sj_file_system import CsvManager

In [2]:
right_hand_data_dir_path = "/Users/yoonseojin/Statistics_sj/CLMN/Replay_Exp/experiment/20210310(Sequence test)/right hand"
file_name = "stimulus_seojin_1"

In [48]:
stimuluses = []
responses = []
for i in range(0, 8):
    stimulus_file_name = "stimulus_seojin_" + str(i)
    response_file_name = "response_seojin_" + str(i)
    stimuluses.append( CsvManager(dir_path=right_hand_data_dir_path, file_name=stimulus_file_name).read_csv_from_pandas()[2:-1] )
    responses.append( CsvManager(dir_path=right_hand_data_dir_path, file_name=response_file_name).read_csv_from_pandas() )

stimuluses[-1] = stimuluses[-1][:-1]

,Step,Event_Type,Stimulus,display_seconds,start_seconds
2,0,single text,4,0.5,0.026075
3,1,ISI,+,2.0,0.554138
4,2,single text,2,0.5,2.571008
5,3,ISI,+,6.0,3.087786
6,4,single text,1,0.5,9.108768
...,...,...,...,...,...
117,115,ISI,+,4.0,474.716266
118,116,single text,3,0.5,478.730583
119,117,Bundle Interval,...,10.0,479.246190
120,118,seq texts,"['1', '4', '2', '3', '1']",15.0,489.285206
121,119,ISI,+,21.0,490.598941